<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>permissionscope-worker-replay</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/PermissionScope.Windows/PermissionScope.Windows.csproj" />
  </ItemGroup>
</Project>
